authorName: datalama
experimentName: Train_Sentiment_Extractor
trialConcurrency: 1
maxExecDuration: 36h
maxTrialNum: 1
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
logDir: /root/ml-experiment-pipeline/experiments
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
  gpuIndices: "0,1,2,3"
# assessor:
#     builtinAssessorName: Medianstop
#     classArgs:
#       optimize_mode: maximize
#       start_step: 15
trial:
  command: python autotrainer.py --task_name "sentiment-extraction" \
                                --data_dir "data/step-04" \
                                --output_dir "ckpt/step-04" \
                                --num_train_epochs "3" \
                                --per_device_train_batch_size 32 \
                                --per_device_eval_batch_size 32 \
                                --overwrite_output_dir \
                                --do_train \
                                --do_eval \
                                --do_predict \ 
                                --evaluate_during_training \
                                --logging_first_step
  codeDir: .
  gpuNum: 1
#localConfig:
#  maxTrialNumPerGpu:  2